### PR TITLE
Add adapter class for Spigot 1.8.7. Solves #15

### PR DESCRIPTION
**Pull request by OxLemonxO**
Solves #15

### CODE REVIEW

**Comment by WickedGamingUK** [comment]
The source code would be useful instead of just a compiled class. Pastebin it perhaps?

**Comment by OxLemonxO** [comment]
The source is not available. I just copied it from the official WorldEdit repo at
https://github.com/sk89q/WorldEdit/tree/master/worldedit-bukkit

**Comment by WickedGamingUK** [comment]
Oh, alright then - I thought this was something that you created yourself.

We'll just need Prozza to test this and see if it's compatible.

**Comment by OxLemonxO** [comment]
@JeromSar

**Comment by JeromSar** [comment]
Thanks!

**Pull request merged**
